import ExcelJS from 'exceljs';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { AnalyzedProduct } from './analytics';

const getBase64ImageFromUrl = async (imageUrl: string): Promise<string | null> => {
  if (!imageUrl) return null;
  try {
    const res = await fetch(`/api/proxy?url=${encodeURIComponent(imageUrl)}&image=true`);
    const data = await res.json();
    return data.base64 || null;
  } catch (err) {
    console.error('Failed to fetch base64 image', err);
    return null;
  }
};

export async function exportToExcel(products: AnalyzedProduct[], brandName: string) {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Deep AI Analysis');

  sheet.columns = [
    { header: 'Image', key: 'image', width: 25 },
    { header: 'Product Name', key: 'title', width: 50 },
    { header: 'Price', key: 'price', width: 15 },
    { header: 'Rating', key: 'rating', width: 15 },
    { header: 'Reviews', key: 'reviews', width: 15 },
    { header: 'Demand Forecast', key: 'demand', width: 20 },
    { header: 'Repurchase Value', key: 'repurchase', width: 20 },
    { header: 'Review Deficit (to 4.8★)', key: 'deficit', width: 25 }
  ];

  // Make header bold
  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).height = 30;
  sheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'center' };

  // Add rows with images
  for (let i = 0; i < products.length; i++) {
    const p = products[i];
    const rowIndex = i + 2; // +2 because row 1 is header
    
    sheet.getRow(rowIndex).height = 100;
    
    sheet.getCell(`B${rowIndex}`).value = p.title;
    sheet.getCell(`C${rowIndex}`).value = p.price;
    sheet.getCell(`D${rowIndex}`).value = p.ratingValue;
    sheet.getCell(`E${rowIndex}`).value = p.reviewsCount;
    sheet.getCell(`F${rowIndex}`).value = p.demandStatus;
    sheet.getCell(`G${rowIndex}`).value = p.repurchaseValue;
    sheet.getCell(`H${rowIndex}`).value = p.reviewDeficit;

    // Center align data
    sheet.getRow(rowIndex).alignment = { vertical: 'middle', wrapText: true };

    // Fetch and embed image
    if (p.image) {
      const base64 = await getBase64ImageFromUrl(p.image);
      if (base64) {
        const imageId = workbook.addImage({
          base64: base64,
          extension: 'png', // fallback extension
        });
        
        sheet.addImage(imageId, {
          tl: { col: 0, row: rowIndex - 1 },
          ext: { width: 100, height: 100 },
          editAs: 'oneCell'
        });
      }
    }
  }

  // Trigger download
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${brandName}_Deep_Analysis.xlsx`;
  a.click();
  window.URL.revokeObjectURL(url);
}

export async function exportToPDF(products: AnalyzedProduct[], brandName: string) {
  const doc = new jsPDF('landscape');

  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text(`Deep AI Executive Summary: ${brandName}`, 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by ScrapeX Engine | ${new Date().toLocaleDateString()}`, 14, 28);

  const totalProducts = products.length;
  const highDemand = products.filter(p => p.demandStatus === 'High Demand').length;
  const highRepurchase = products.filter(p => p.repurchaseValue === 'High').length;
  const avgRating = totalProducts > 0 
    ? (products.reduce((a, b) => a + b.ratingValue, 0) / totalProducts).toFixed(2) 
    : 0;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Analyzed: ${totalProducts} | Avg Rating: ${avgRating}★ | High Demand: ${highDemand} | High Repurchase: ${highRepurchase}`, 14, 40);

  // Prepare table data
  const tableData = products.map(p => [
    '', // Empty cell for image placeholder
    p.title.substring(0, 50) + (p.title.length > 50 ? '...' : ''),
    p.price,
    `${p.ratingValue}★ (${p.reviewsCount})`,
    p.demandStatus,
    p.repurchaseValue,
    p.reviewDeficit > 0 ? `Needs ${p.reviewDeficit}` : 'Target Met'
  ]);

  // Pre-fetch all images
  const base64Images = await Promise.all(products.map(p => getBase64ImageFromUrl(p.image)));

  (doc as any).autoTable({
    startY: 45,
    head: [['Image', 'Product', 'Price', 'Rating', 'Demand', 'Repurchase', 'Deficit (4.8★)']],
    body: tableData,
    theme: 'grid',
    styles: { fontSize: 9, valign: 'middle', minCellHeight: 30 },
    columnStyles: {
      0: { cellWidth: 30 } // Image column width
    },
    headStyles: { fillColor: [139, 92, 246] }, // Purple-500
    didDrawCell: function(data: any) {
      if (data.column.index === 0 && data.cell.section === 'body') {
        const rowIndex = data.row.index;
        const imgData = base64Images[rowIndex];
        
        if (imgData) {
          try {
             // Draw image inside the cell
             doc.addImage(imgData, 'JPEG', data.cell.x + 2, data.cell.y + 2, 26, 26);
          } catch(e) {
             console.error("PDF Image Error", e);
          }
        }
      }
    }
  });

  doc.save(`${brandName}_Executive_Summary.pdf`);
}
